name: 'Subir artifactory'
description: 'upload tag a gh artifactory'

inputs:
  target:
    description: 'Environment type (dev or prod)'
    required: true
    default: 'dev'

outputs:
  tag:
    description: 'image tag extracted'
    value: ${{ steps.get_gh_image_tag.outputs.version }}

runs: 
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Image Tag
      id: get_gh_image_tag
      shell: bash
      run: | 
        version=$(jq -r .version package.json)
        if [[ "${{ inputs.target }}" == "dev" ]]; then
          version="${version}-snapshot"
        fi
        echo "version=${version}" >> "$GITHUB_OUTPUT"
        echo $GITHUB_OUTPUT
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
       name: my-artifact
       path: my_file.txt
       retention-days: 5
